=== etn-corp/github-artifacts-repo/target/TargetAccountPlanner/WEB-INF/classes/conf/ProfileConfiguration.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT acl (class, deny-url, config, uid, pw)>
<!ATTLIST acl
	name CDATA #REQUIRED
>
<!ELEMENT class (#PCDATA)>
<!ELEMENT config (#PCDATA)>
<!ELEMENT default (deny-url)>
<!ELEMENT dcs-profile (default, acl+)>
<!ELEMENT deny-url (#PCDATA)>
<!ELEMENT uid (#PCDATA)>
<!ELEMENT pw (#PCDATA)>

=== etn-corp/github-artifacts-repo/src/main/resources/prod/conf/ProfileConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dcs-profile SYSTEM "ProfileConfiguration.dtd">
<dcs-profile>
	<default>
	    <deny-url>https://dummy.eaton.com</deny-url>
	</default>
	<acl name="PORTAL">
		<!-- Toggle the entries below to switch between portal servers (new is IdentityServerACLProfile) -->
		<class>com.eaton.securedocs.IdentityServerACLProfile</class>
		<!--<class>com.eaton.securedocs.JOEACLProfile</class>-->
		<deny-url>https://dummy.eaton.com</deny-url>
		<config>/conf/smrcACL.properties</config>
		<uid></uid>
		<pw></pw>
	</acl>
</dcs-profile>
